version: "3"
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - wordpress
    volumes:
      - ./nginx/nginx.crt:/etc/nginx/nginx.crt
      - ./nginx/nginx.key:/etc/nginx/nginx.key

  wordpress:
    build:
      context: ./wordpress
      dockerfile: Dockerfile
    volumes:
      - wordpress_data:/var/www/html

volumes:
  wordpress_data:
