version: '3.8'

services:
  mariadb:
    restart: always
    build: ./requirements/mariadb
    container_name: mariadb_container
    image: mariadb
    env_file:
        ./.env
    volumes:
      - mariadb_data:/var/lib/mysql

  wordpress:
    restart: always
    depends_on:
        - mariadb
    build: ./requirements/wordpress
    container_name: wordpress_container
    image: wordpress
    env_file:
        ./.env
    volumes:
      - wordpress_data:/var/www/wordpress

  nginx:
    restart: always
    depends_on:
      - wordpress
    build: ./requirements/nginx
    image: nginx
    container_name: nginx_container
    ports:
      - 443:443
    volumes:
      - wordpress_data:/var/www/wordpress
  
  website:
    build: ./requirements/bonus/website
    container_name: website_container
    image : website
    ports:
      - 82:82
    volumes:
      - website:/var/www/pages
    restart : always

  redis:
    restart: always
    init:  true
    build : ./requirements/bonus/redis
    image: redis
    container_name: redis_container
    ports:
      - 6379:6379
    
  code_space:
      build: ./requirements/bonus/code_space
      container_name: code_space_container
      image: code_space
      ports:
        - "8080:8080"

  adminer:
      build: ./requirements/bonus/adminer
      container_name: adminer_container
      image: adminer
      ports:
        - "8000:8000"

  ftp:
    container_name: ftp_container
    init: true
    image: ftp
    build: ./requirements/bonus/ftp
    restart: always
    ports:
      - 21:21
      - 20:20
    volumes:
        - wordpress_data:/var/www/wordpress

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/yoel-idr/data/wordpress
      o: bind
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/yoel-idr/data/mysql
  website:

networks:
  default: