ARG OS_VERSION=3.18
FROM alpine:${OS_VERSION}

ENV DB_NAME=wordpress
ENV DB_USER=joseph
ENV URL_NAME=joseph.42.fr
ENV ADMIN_USER=joseph
ENV USER_EMAIL=joseph@gmail.com
ENV DB_PASS=dexter
ENV ROOT_PASS=dexter

ADD ./tools/mariadb-setup.sh /
RUN apk update ; apk add vim openrc mysql mysql-client php-mysqli ;

ENTRYPOINT [ "sh", "mariadb-setup.sh" ]

CMD ["mysqld", "--user=root"]