ARG OS_VERSION=3.18
FROM alpine:${OS_VERSION}

RUN apk update ; apk add vim nginx openrc php-fpm php-mysqli curl php \ 
                        php-curl php-json php-phar php-mbstring php-dom; \
                        mkdir -p /var/www/wordpress

WORKDIR /var/www/wordpress
ADD "https://wordpress.org/latest.tar.gz" .
ADD ./tools/wp-config.php .
ADD ./tools/setup-wordpress.sh .
RUN tar -xzf latest.tar.gz --strip-components=1; rm -f latest.tar.gz

ENTRYPOINT [ "sh", "setup-wordpress.sh" ]

CMD [ "php-fpm81" , "-F"]