FROM alpine:3.18

RUN apk update

RUN apk --no-cache add \
    php7 \
    php7-fpm \
    php7-mysqli \
    php7-json \
    php7-session \
    php7-dom \
    php7-xml \
    php7-curl \
    php7-mbstring \
    php7-gd \
    php7-openssl \
    curl \
    tar

RUN apk add openrc openssl ; mkdir /run/openssl ; touch /run/openssl/softlevel
