ARG OS_VERSION=3.18
FROM alpine:${OS_VERSION}

ENV DB_NAME=wordpress
ENV DB_USER=joseph
ENV URL_NAME=yoelidr.42.fr
ENV ADMIN_USER=joseph
ENV USER_EMAIL=joseph@gmail.com
ENV DB_PASS=dexter
ENV ROOT_PASS=dexter
ENV DATABASE_HOST=mariadb

RUN apk update ; apk add vim nginx openrc php-fpm php-mysqli curl php \ 
                        php-curl php-json php-phar php-mbstring php-dom; \
                        mkdir -p /var/www/wordpress
WORKDIR /var/www/wordpress
ADD "https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar" .
ADD "https://wordpress.org/latest.tar.gz" .
ADD ./tools/wp-config.php .
ADD ./tools/setup-wordpress.sh .

RUN tar -xzf wordpress.tar.gz --strip-components=1; \
    rm wordpress.tar.gz; \
    chmod +x wp-cli.phar; \
    mv wp-cli.phar /usr/local/bin/wp; \

ENTRYPOINT [ "sh", "setup-wordpress.sh" ]

CMD [ "php-fpm81" , "-F"]