FROM alpine:3.18

RUN apk update ; apk add vim ; apk add nginx ; apk add openrc --no-cache ; apk add openssl ; rm -rf /var/cache/apk/* 
RUN mkdir /var/www/html
RUN mkdir /run/openrc ; touch /run/openrc/softlevel ; mkdir /etc/nginx/ssl

COPY ./tools/index.html /var/www/html
COPY ./tools/nginx.conf /etc/nginx/http.d
EXPOSE 8000
CMD ["nginx", "-g", "daemon off;"]
